
version: '3.5'

services:
  nginx:
    image: nginx:1.18.0
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - php
    container_name: project_nginx

  php:
    build:
        context: .
        dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db
    container_name: project_app

  php-cli:
    build:
      context: .
      dockerfile: _docker/php_cli/Dockerfile
    volumes:
      - ./:/var/www/
    links:
      - php
    container_name: project_php_cli


  mysql:
      image: mysql:8.0
      restart: always
      environment:
          MYSQL_DATABASE: db2
          MYSQL_ROOT_PASSWORD: root
      ports:
          - 3306:3306
      container_name: project_mysql

